apiVersion: v1
kind: Service
metadata:
  name: maven-webapp-runner
  labels:
    app: maven-webapp-runner
    service: maven-webapp-runner
spec:
  ports:
  - port: 8080
    targetPort: 8086
    name: http
  selector:
    app: maven-webapp-runner
